version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  service_produits:
    build: .
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://mongo:27017/products
      KAFKA_BROKER: kafka:9092
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - kafka

volumes:
  mongo-data:
