version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  service_clients:
    build: ../services/service_clients
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    ports:
      - "3000:3000"

  service_produits:
    build: ../services/service_produits
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    ports:
      - "3002:3002"

  service_commande:
    build: ../services/service_commande
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    ports:
      - "3001:3001"
