version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clients
    volumes:
      - clients_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d clients"]
      interval: 10s
      timeout: 5s
      retries: 5

  service_clients:
    build:
      context: ../../
      dockerfile: services/service_clients/Dockerfile.prod
    environment:
      PORT: 3000
      DATABASE_URL: postgres://user:password@db:5432/clients
      KAFKA_BROKER: kafka:9092
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  clients_data: