version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  service_commande:
    build: .
    environment:
      PORT: 3001
      DATABASE_URL: postgres://user:password@db:5432/orders
      KAFKA_BROKER: kafka:9092
    ports:
      - "3001:3001"
    depends_on:
      - db
      - kafka

volumes:
  data:
