name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      #   run: |
      #     corepack enable
      #     corepack prepare pnpm@8.15.5 --activate

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Run tests
        run: pnpm -r test