name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'services/service_clients/**'
      - 'services/service_commande/**'
      - 'services/service_produits/**'
      - 'services/service_webshop/**'
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm -r test
        
      - name: Build
        run: pnpm -r build