name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18


      - name: Install Node dependencies
        run: |
          cd services/service_clients && npm ci
          cd ../service_commande && npm ci
          cd ../service_produits && npm ci

      - name: Run Node tests
        run: |
          cd services/service_clients && npm test
          cd ../service_commande && npm test
          cd ../service_produits && npm test
