name: Service Clients CI

on:
  push:
    paths:
      - 'services/service_clients/**'
      - 'libs/kafka/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm --filter service_clients test
        
      - name: Build
        run: pnpm --filter service_clients build
