name: Service Commande CI

on:
  push:
    paths:
      - 'services/service_commande/**'
      - 'libs/kafka/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Enable pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm --filter service_commande test
        
      - name: Build
        run: pnpm --filter service_commande build
